parameters:
    # Managers
    innova_non_digital.manager.non_digital_resource.class:   Innova\NonDigitalResourceBundle\Manager\NonDigitalResourceManager
    
    # Form types
    innova_non_digital.form.type.non_digital_resource.class: Innova\NonDigitalResourceBundle\Form\NonDigitalResourceType

    # Listeners
    innova_non_digital.listener.non_digital_resource.class:  Innova\NonDigitalResourceBundle\Listener\Resource\NonDigitalResourceListener