services:
  innova_non_digital.listener.non_digital_resource:
    class: %innova_non_digital.listener.non_digital_resource.class%
    calls:
      - [setContainer, ["@service_container"]]
    tags:
      - { name: kernel.event_listener, event: open_innova_non_digital_resource,        method: onNonDigitalResourceOpen }
      - { name: kernel.event_listener, event: create_form_innova_non_digital_resource, method: onNonDigitalResourceCreateForm }
      - { name: kernel.event_listener, event: delete_innova_non_digital_resource,      method: onNonDigitalResourceDelete }
      - { name: kernel.event_listener, event: create_innova_non_digital_resource,      method: onNonDigitalResourceCreate }
      - { name: kernel.event_listener, event: copy_innova_non_digital_resource,        method: onNonDigitalResourceCopy }